banks:
  - id: "387952"
    name: "eAcquirerBank"
    url: "https://ebanksep-be.azurewebsites.net/api/payment/external-pay"
  - id: "497335"
    name: "eIssuerBank"
    url: "https://issuer-ebanksep-be.azurewebsites.net/api/payment/external-pay"
server:
  port: 8081
tls:
  certFile: "/etc/ssl/certs/pcc.crt"
  keyFile: "/etc/ssl/private/pcc.key"