banks:
  - id: "387952"
    name: "eAcquirerBank"
    url: "http://localhost:8080/api/payment/external-pay"
  - id: "497335"
    name: "eIssuerBank"
    url: "http://ebanksep-be-issuer:8080/api/payment/external-pay"
server:
  port: 8081
tls:
  certFile: "/etc/ssl/certs/pcc.crt"
  keyFile: "/etc/ssl/private/pcc.key"