banks:
  - id: "387952"
    name: "eAcquirerBank"
    url: "https://acquirer.example.com/api/payments/pay"
  - id: "497335"
    name: "eIssuerBank"
    url: "https://issuer.example.com/api/payments/pay"
server:
  port: 8081
tls:
  certFile: "/etc/ssl/certs/pcc.crt"
  keyFile: "/etc/ssl/private/pcc.key"